
INSERT INTO jokes (message) VALUES
('Why don’t scientists trust atoms? Because they make up everything!'),
( 'I told my wife she was drawing her eyebrows too high. She looked surprised.'),
( 'Why don’t skeletons fight each other? They don’t have the guts.'),
('I would avoid the sushi if I was you. It’s a little fishy.'),
('Want to hear a joke about construction? I’m still working on it.');
-- yes, the jokes are generated by AI .... I know
